// init hooks
exports.LIFE_GOES_ON = 'LIFE_GOES_ON'; // 《All Eyez On Me》

// build hooks
exports.BUILD_START = 'BUILD_START';
exports.BUILD_END = 'BUILD_END';
exports.BUILD_CHANGE = 'BUILD_CHANGE';

// dependencies hooks
exports.DEPEND_GRAPH = 'DEPEND_GRAPH';

// compile hooks
exports.COMPILER_PARSE_BEFORE = 'COMPILER_PARSE_BEFORE';
exports.COMPILER_PARSE_AFTER = 'COMPILER_PARSE_AFTER';
exports.COMPILER_TRANSFORM_BEFORE = 'COMPILER_TRANSFORM_BEFORE';
exports.COMPILER_TRANSFORM_AFTER = 'COMPILER_TRANSFORM_AFTER';

// compress hooks
exports.COMPRESS_BEFORE = 'COMPRESS_BEFORE';
exports.COMPRESS_AFTER = 'COMPRESS_AFTER';
